# -*- coding: utf-8 -*-
"""costoEinstein.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P4X0VE-WgzQyEq9zmcwGQjw8PqL8M4GK
"""

class Casa:
    color=""
    nacionalidad=""
    def __init__(self,c,n):
        self.color=c
        self.nac=n

colores=["blanco","verde","azul"]
nacion=["Sueco","Danes","Aleman"]

'''
TODAS LAS POSIBLES COMBINACIONES (se repiten en cada casa)
for contCasa in range(2):
    for c in colores: #combinaciones color nacion
        for n in nacion:
            print("Casa n",contCasa+1," ",c,n)
'''
'''
#apoyarnos de conjuntos, para que no pueda haber elementos repetidos
#EJEMPLOS DE CONJUNTOS
a=[1,2,3,4,5]
b=[1,2,3,4,5] #listas
a=set(a)
b=set(b) #los conviertes a conjuntos
print(a,b)
a=b      #aqui solo se va a imprimir una serie, ya que no puede haber elementos
print(a) #repetidos
'''
#Einstein
colores=set(["Azul","Verde","blanco","Rojo"])
nacion=set(["Sueco","Danes","Aleman","Britanico"])
mascota=set(["perro","gato","tortuga","Pez"])#meter el valor directamente en los conjuntos
bebida=set([])
cigarrillos=set([])

for cc1 in colores:
    for cc2 in nacion-set([cc1]):
        for cc3 in mascota-set([cc2]):
            if(cc2!=cc3):   #depurar repetidos como principiante xd
                print(cc1,cc2,cc3)

class Casa:
    color=""
    nacionalidad=""
    def __init__(self,c,n):
        self.color=c
        self.nac=n

colores=["blanco","verde","azul"]
nacion=["Sueco","Danes","Aleman"]

'''
TODAS LAS POSIBLES COMBINACIONES (se repiten en cada casa)
for contCasa in range(2):
    for c in colores: #combinaciones color nacion
        for n in nacion:
            print("Casa n",contCasa+1," ",c,n)
'''
'''
#apoyarnos de conjuntos, para que no pueda haber elementos repetidos
#EJEMPLOS DE CONJUNTOS
a=[1,2,3,4,5]
b=[1,2,3,4,5] #listas
a=set(a)
b=set(b) #los conviertes a conjuntos
print(a,b)
a=b      #aqui solo se va a imprimir una serie, ya que no puede haber elementos
print(a) #repetidos
'''
#Einstein
colores=set(["Azul","Verde"])
nacion=set(["Sueco","Danes"])
mascota=set(["perro","gato"])#meter el valor directamente en los conjuntos
bebida=set(["ron","whisky"])
cigarrillos=set(["marca2","marca1"])

'''
colores=set(["Azul","Verde","Rojo","Amarillo"])
nacion=set(["Sueco","Danes","Aleman","Britanico"])
mascota=set(["perro","gato","tortuga","Hamster"])#meter el valor directamente en los conjuntos
bebida=set(["ron","whisky","agua","refresco"])
cigarrillos=set(["",""])
'''

cont=0
for cc1 in colores:
    for cc2 in nacion-set([cc1]):
        for cc3 in mascota-set([cc2]): 
            for cc4 in bebida-set([cc3]):
                for cc5 in cigarrillos-set([cc4]):
                  if(cc4!=cc5):   #depurar repetidos como principiante xd
                    cont=cont+1
                    print(cont,cc1,cc2,cc3,cc4,cc5)